Xext: fix selinux build failure
The server builds with -Werror=missing-braces, causing

xselinux_hooks.c: In function 'SELinuxFlaskInit':
xselinux_hooks.c:851:12: error: missing braces around initializer
[-Werror=missing-braces]
xselinux_hooks.c:851:12: error: (near initialization for
'avc_option.<anonymous>') [-Werror=missing-braces]
cc1: some warnings being treated as errors

Source is libselinux' libselinux-rhat.patch which changes struct selinux_opt
from { int, char * } to { int, union { char*, char** }}.

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>